#ifndef ALPHA_ZERO_API_API_CPP_ALPHAZEROAPI_DEFAULT_SIMPLE_DESERIALIZER_H_
#define ALPHA_ZERO_API_API_CPP_ALPHAZEROAPI_DEFAULT_SIMPLE_DESERIALIZER_H_

#ifdef DEFAULT_DESERIALIZER
  #include "AlphaZeroAPI/include/deserializer.h"
#endif  // DEFAULT_DESERIALIZER

#ifdef DEFAULT_DESERIALIZER

namespace alphazero::game::api {}  // namespace alphazero::game::api

#endif  // DEFAULT_DESERIALIZER

#endif  // ALPHA_ZERO_API_API_CPP_ALPHAZEROAPI_DEFAULT_SIMPLE_DESERIALIZER_H_
